baseURL = "https://dteslya.engineer"

title = "Dmitry Teslya"
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "axiom"

paginate = 10
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:filename"

[params]
mainSections = ["posts"]
copyrightYear = 2018
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
#dateFormat = "Jan 2, 2006 3:04PM"
dateFormat = "Jan 2, 2006"
highlight = "dark"
maxWidthTitle = "max-w-4xl"
maxWidthContent = "max-w-4xl"

[params.brand]
domain = "dteslya.engineer"
email = "dmitry.teslya@gmail.com"

[params.social]
facebook = "https://www.facebook.com/dteslya"
github = "https://github.com/dteslya"
instagram = "https://instagram.com/dteslya"
linkedin = "https://www.linkedin.com/in/dteslya"
#pinterest = "https://www.pinterest.com/user"
#stackoverflow = "https://stackoverflow.com/users/user"
twitter = "https://twitter.com/grimward"
#youtube = "https://www.youtube.com/user"
footer = ["twitter", "facebook", "github", "linkedin", "instagram"]

[params.services]
googleAnalyticsId = "UA-131564955-1"
googleTagManagerId = ""
googleAdsId = ""
googleAdsenseId = ""
googleAdsenseAdSlotId = ""
googleAdsenseLoad = ""
googleAdsConversionId = ""
googleAdsConversionValue = 0
facebookApp = ""
facebookPixel = ""
#disqusShortname = "dteslya"

[params.staticman]
  endpoint = "https://dteslya-engineer-staticman.herokuapp.com/v2/entry"
  username = "dteslya"
  repository = "dteslya-engineer"
  branch = "staticman"

# [params.logo]
# inline = true
# path = "image/brand/logo.svg"

[params.image]
width = "2048"
height = "1024"
faviconIco = "favicon.ico"
faviconAlt = "image/brand/favicon.png"
icon1To1 = "image/brand/icon-1-1.png"
icon2To1 = "image/brand/icon-2-1.png"
default = "image/page-default.webp"

[params.font]
type = ""
path = ""
files = []

[params.cdn]
provider = "local"
type = "image"

[params.cloudinary]
host = "https://res.cloudinary.com/CLOUD_NAME/"
version = ""
image = "image/upload/"
raw = "raw/upload/"
video = "video/upload/"

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
lineNos = false
# lineNumbersInTable = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 1

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.main]]
url = "/about/"
name = "About"
weight = 2

[languages]
[languages."en"]
weight = 1
languageName = "English"